### ISSUE TITLE
Problem with Nextcloud Database on Raspberry Pi 4

### ISSUE THREAD

**Issue by alexjmccoy** [DoTheEvo/selfhosted-apps-docker#10]
I'm having an issue where my database container restarts with the following error:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec --transaction-isolation=READ-COMMITTED: No such file or directory
[cmd] --transaction-isolation=READ-COMMITTED exited 127
Caught SIGTERM signal!
cat: /var/run/mysqld/mysqld.pid: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I followed the tutorial quite closely. Here is my `docker-compose.yml`. The only modification is the different MariaDB image for the Raspberry Pi architecture.

```
version: '3'
services:

  nextcloud-db:
    image: linuxserver/mariadb:arm32v7-latest
    container_name: nextcloud-db
    hostname: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./nextcloud-data-db:/var/lib/mysql

  nextcloud-redis:
    image: redis:5.0.9-alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    hostname: nextcloud-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - ./nextcloud-data/:/var/www/html

  nextcloud-web:
    image: nginx:alpine
    container_name: nextcloud-web
    hostname: nextcloud-web
    restart: unless-stopped
    volumes:
      - ./nextcloud-data/:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    hostname: nextcloud-cron
    restart: unless-stopped
    volumes:
      - ./nextcloud-data/:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
```

My `.env` file:

```
# GENERAL
MY_DOMAIN=nextcloud.mydomain.com
DOCKER_MY_NETWORK=master
TZ=America/New_York

# NEXTCLOUD-MARIADB
MYSQL_ROOT_PASSWORD=<big_password>
MYSQL_PASSWORD=<big_password>
MYSQL_DATABASE=nextcloud
MYSQL_USER=nextcloud

# NEXTCLOUD
MYSQL_HOST=nextcloud-db
REDIS_HOST=nextcloud-redis

# USING SENDGRID FOR SENDING EMAILS
#MAIL_DOMAIN=nextcloud.mydomain.com
#MAIL_FROM_ADDRESS=nextcloud
#SMTP_SECURE=ssl
#SMTP_HOST=smtp.sendgrid.net
#SMTP_PORT=465
#SMTP_NAME=apikey
#SMTP_PASSWORD=<sendgrid-api-key-goes-here>
```

Any ideas? I can get to the Nextcloud "Create admin account" page, but after that I get the error:

> Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve
