### ISSUE TITLE
Update to Nextcloud+Redis>=6

### ISSUE THREAD

**Issue by ahgraber** [DoTheEvo/selfhosted-apps-docker#19]
I've been experimenting with transitioning to Redis>6.  Here are the changes I had to make to your setup:

users.acl:
```
user default on >SOME_STRONG_PASSWORD ~* &* +@all 
```

redis.conf (note: incomplete; these are just the modifications I found were required):
```
...
bind nextcloud-redis  # bind to redis container-name
...
aclfile /run/secrets/ACL_SECRET_NAME
...
```

docker-compose.yml
```yml
secrets:
  ACL_SECRET_NAME:
    - ./users.acl

services:
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    secrets:
      - ACL_SECRET_NAME
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
```
